version: '3.7'
networks:
  docker-compose-local:
    driver: bridge

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
     - "1883:1883"
     - "8883:8883"
     - "9001:9001"
    deploy:
      restart_policy:
        condition: on-failure